[package]
name = "nice-engine"
version = "0.1.0"
authors = ["IcyDefiance <icydefiance@gmail.com>"]
edition = "2018"

[workspace]
members = ["capi"]

[dependencies]
log = "0.4.7"
vulkano = "0.13.0"
vulkano-shaders = "0.13.0"
vulkano-win = { version = "0.13.0", optional = true }
winit = { version = "0.19.1", optional = true }

[features]
default = ["window"]
window = ["vulkano-win", "winit"]
