[package]
name = "sandbox"
version = "0.1.0"
authors = ["IcyDefiance <icydefiance@gmail.com>"]
edition = "2018"

[dependencies]
cgmath = "0.17.0"
nice-engine = { path = "../.." }
simplelog = "0.5"
winit = "0.20.0-alpha4"
